### ISSUE TITLE
Aufsummierte Member Payments

### ISSUE THREAD

**Issue by schmijos** [coredump-ch/interna#1]
Es wäre bequem, wenn aus dem Admin-Interface ersichtlich wäre, wer bis wann seine Mitgliederbeiträge bezahlt hat. Für diese Berechnung fehlt jedoch eine Kategorie bei den Einzahlungen: {verdiener, nichtverdiener, sonstige}. Eventuell wäre es noch besser, diese Information beim Membership unterzubringen.

**Comment by dbrgn** [comment]
@schmijos wollen wir uns mal zusammensetzen um das datenmodell betreffend finanzen zu überarbeiten?

**Comment by dbrgn** [comment]
Close, die Zahlungen werden nicht mehr über die Interna-Seite erfasst.
