### ISSUE TITLE
Crowdfunding-Tool

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/interna#14]
- User können ein Crowdfunding-Projekt eintragen mit Bild und Beschreibung (Login required)
- Man kann sich als "Funder" eintragen, optional mit Ablaufdatum (Login nicht nötig)
- Ein Balken zeigt an, wie viele Prozent schon zusammen sind
- Die Projekte werden in einem Raster auf der Seite angeordnet

**Comment by dbrgn** [comment]
Sowas:

![Mockup](https://tmp.dbrgn.ch/screenshots/20170615133446-00k2f6l0.png)

**Comment by rnestler** [comment]
Als erster Schritt können wir auch die Crowdfundings im [Forum](https://forum.coredump.ch) managen.

**Comment by dbrgn** [comment]
Grösstenteils fertig: #17
