### ISSUE TITLE
Mitglieder-Count

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/interna#3]
Bei der Liste der Aktiv- und Ehemals-Mitglieder jeweils in der Überschrift die Anzahl anzeigen.

Beispiel: "Aktivmitglieder (19)"

@schmijos, hast du Lust das zu übernehmen? Ist recht trivial :)

**Comment by dbrgn** [comment]
@schmijos lust, das irgendwann mal zu machen? :)

**Comment by schmijos** [comment]
Ja schon :-P auch alles andere. Aber die Zeit... Ev. hab ich am Wochenende mal Zeit.

**Comment by dbrgn** [comment]
Das Problem kenne ich :D
