### ISSUE TITLE
Pipenv

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/interna#30]
Somehow I'm not really happy with Pipenv. Lots of bugs, harder to integrate into our deployment. Shall we remove it?

What do you think @rnestler?

**Comment by rnestler** [comment]
I don't think it is that horrible and actually works quite well for applications. What are the exact problems you have with it?

**Comment by dbrgn** [comment]
I didn't say it's horrible, just that I experienced bugs (like, actual bugs where I couldn't install the packages) multiple times. They were fixed in the meantime, but Pipenv relies on internal pip functions not intended to be used from other tools, and sometimes breaks when pip updates.

Also, our current deployment setup isn't updated yet for Pipenv it seems :)
